---
- hosts: "{{ target_hosts }}"
  gather_facts: no
  vars_prompt:
    - name: "filename"
      prompt: "Введите имя файла"
      private: no
    - name: "target_hosts"
      prompt: "Введите целевые хосты"
      private: no
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - /home/ermek/ansible/secret/secret.yml
  tasks:
    - name: Ensure results file exists
      file:
        path: /home/ermek/{{ filename }}.csv
        state: touch
      delegate_to: localhost
    - name: Get CPU model
      shell: cat /proc/cpuinfo | grep 'model name' | head -1
      register: cpu_model

    - name: Get RAM model
      shell: dmidecode --type memory | grep 'Part Number' | head -1
      register: ram_model

    - name: Get disk model
      shell: cat /sys/block/sda/device/model
      register: disk_model

    - name: Get OS version
      shell: lsb_release -d
      register: os_version

    - name: Get video card vendor
      shell: lspci | grep VGA | cut -d ':' -f3 | cut -d '[' -f2 | cut -d ']' -f1
      register: video_card_vendor

    - name: Get video card model
      shell: lspci | grep VGA | cut -d ':' -f3 | cut -d ']' -f2
      register: video_card_model

    - name: Get Motherboard model
      shell: dmidecode -t baseboard | grep 'Product Name'
      register: motherboard_model
      
    - name: Save result to file
      delegate_to: localhost
      lineinfile:
        path: "/home/ermek/{{ filename }}.csv"
        line: "{{ inventory_hostname }},{{ cpu_model.stdout }},{{ motherboard_model.stdout }},{{ ram_model.stdout }},{{ disk_model.stdout }},{{ os_version.stdout }},{{ video_card_vendor.stdout }},{{ video_card_model.stdout }}"