---
- name: Accept SSH fingerprint
  hosts: "{{ target_hosts }}"
  gather_facts: no
  #vars_prompt:
   # - name: "target_hosts"
   #   prompt: "Введите хосты, на которых нужно сохранить все fingerprintы"
    #  private: no
    #- name: "filename"
     # prompt: "Введите название файла, куда записать результаты"
      #private: no
    #- name: "secret"
    #  prompt: "Какие пароли используем?"
    #  private: no
  #become: true
  #become_user: root
  #become_method: sudo
  #vars_files:
    #- /home/ermek/ansible/secret/{{ secret }}.yml
  tasks:
    - name: Run ssh-keyscan on all hosts and save fingerprints
      shell: ssh-keyscan -H {{ inventory_hostname }} >> /home/ermek/.ssh/known_hosts
      delegate_to: localhost
      register: scan_result
      ignore_errors: yes

    - name: Create CSV file (only once)
      file:
        path: "/home/ermek/csvfiles/{{ filename }}.csv"
        state: touch
      delegate_to: localhost
      run_once: true

    - name: Write results to CSV file
      lineinfile:
        path: "/home/ermek/csvfiles/{{ filename }}.csv"
        line: "{{ inventory_hostname }}, {{ scan_result.rc == 0 | ternary('done', 'error') }}"
      delegate_to: localhost
