---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure results file exists
      file:
        path: /home/ermek/hardwares2.csv
        state: touch
      delegate_to: localhost

- hosts: NVME
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - /home/ermek/ansible/secret/secret.yml
  tasks:
    - name: Получить информацию о процессоре
      shell: cat /proc/cpuinfo | grep 'model name' | head -1
      register: cpu_info

    - name: Получить информацию о производителе и модели ОЗУ
      shell: dmidecode --type memory | grep 'Part Number' | head -1
      become: yes
      register: ram_info

    - name: Получить информацию о жестком диске
      shell: cat /sys/block/nvme0n1/device/model
      register: disk_info

    - name: Получить информацию о версии и типе операционной системы
      shell: lsb_release -d
      register: os_info

    - name: Сохранить полученные данные в файл CSV
      delegate_to: localhost
      lineinfile:
        path: /home/ermek/hardwares2.csv
        line: "{{ inventory_hostname }},{{ ram_info.stdout.split(':')[1].strip() }},{{ cpu_info.stdout.split(':')[1].strip() }},{{ disk_info.stdout.strip() }},{{ os_info.stdout.split(':')[1].strip() }}"

